FROM openjdk:11-jdk AS builder
WORKDIR source
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
RUN java -Djarmode=layertools -jar app.jar extract

FROM openjdk:11-jre
WORKDIR application
COPY --from=builder source/dependencies ./
COPY --from=builder source/spring-boot-loader ./
COPY --from=builder source/snapshot-dependencies ./
COPY --from=builder source/application ./


ENTRYPOINT ["java","org.springframework.boot.loader.JarLauncher"]

