FROM openjdk:11-jdk AS builder
WORKDIR source
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
RUN jar -xf ./app.jar

FROM openjdk:11-jre
WORKDIR application
COPY --from=builder source/BOOT-INF/lib BOOT-INF/lib
COPY --from=builder source/BOOT-INF/classpath.idx BOOT-INF
COPY --from=builder source/org org

COPY --from=builder source/META-INF META-INF
COPY --from=builder source/META-INF app/META-INF

COPY --from=builder source/BOOT-INF/classes BOOT-INF/classes


ENTRYPOINT ["java","org.springframework.boot.loader.JarLauncher"]

